export const themes = {
  ocean: {
    '--theme-bg-base': '#f0f9ff',
    '--theme-bg-sidebar': '#ffffff',
    '--theme-bg-card': '#ffffff',
    '--theme-bg-elevated': '#e0f2fe',
    '--theme-bg-hover': '#bae6fd',
    '--theme-bg-input': '#ffffff',
    '--theme-primary': '#0ea5e9',
    '--theme-primary-light': '#e0f2fe',
    '--theme-primary-dark': '#0284c7',
    '--theme-text-primary': '#0c4a6e',
    '--theme-text-secondary': '#0369a1',
    '--theme-text-muted': '#7dd3fc',
    '--theme-text-disabled': '#bae6fd',
    '--theme-text-inverse': '#ffffff',
    '--theme-border-default': '#bae6fd',
    '--theme-border-focus': '#0ea5e9',
    '--theme-border-subtle': '#e0f2fe',
    '--theme-success': '#22c55e',
    '--theme-success-light': '#dcfce7',
    '--theme-warning': '#f59e0b',
    '--theme-warning-light': '#fef3c7',
    '--theme-error': '#ef4444',
    '--theme-error-light': '#fee2e2',
    '--theme-info': '#3b82f6',
    '--theme-info-light': '#dbeafe',
    '--theme-chart-1': '#0ea5e9',
    '--theme-chart-2': '#8b5cf6',
    '--theme-chart-3': '#f59e0b',
    '--theme-chart-4': '#22c55e',
    '--theme-chart-5': '#ef4444',
    '--theme-shadow-card': '0 4px 12px rgba(0, 0, 0, 0.06)',
    '--theme-shadow-card-hover': '0 8px 30px rgba(0, 0, 0, 0.08)',
    '--theme-shadow-dropdown': '0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -2px rgba(0, 0, 0, 0.06)',
    '--theme-shadow-modal': '0 20px 25px -5px rgba(0, 0, 0, 0.12), 0 8px 10px -6px rgba(0, 0, 0, 0.08)',
  },
  coral: {
    '--theme-bg-base': '#fff7ed',
    '--theme-bg-sidebar': '#ffffff',
    '--theme-bg-card': '#ffffff',
    '--theme-bg-elevated': '#ffedd5',
    '--theme-bg-hover': '#fed7aa',
    '--theme-bg-input': '#ffffff',
    '--theme-primary': '#f97316',
    '--theme-primary-light': '#ffedd5',
    '--theme-primary-dark': '#ea580c',
    '--theme-text-primary': '#7c2d12',
    '--theme-text-secondary': '#c2410c',
    '--theme-text-muted': '#fdba74',
    '--theme-text-disabled': '#fed7aa',
    '--theme-text-inverse': '#ffffff',
    '--theme-border-default': '#fed7aa',
    '--theme-border-focus': '#f97316',
    '--theme-border-subtle': '#ffedd5',
    '--theme-success': '#22c55e',
    '--theme-success-light': '#dcfce7',
    '--theme-warning': '#f59e0b',
    '--theme-warning-light': '#fef3c7',
    '--theme-error': '#ef4444',
    '--theme-error-light': '#fee2e2',
    '--theme-info': '#3b82f6',
    '--theme-info-light': '#dbeafe',
    '--theme-chart-1': '#f97316',
    '--theme-chart-2': '#8b5cf6',
    '--theme-chart-3': '#f59e0b',
    '--theme-chart-4': '#22c55e',
    '--theme-chart-5': '#ef4444',
    '--theme-shadow-card': '0 4px 12px rgba(0, 0, 0, 0.06)',
    '--theme-shadow-card-hover': '0 8px 30px rgba(0, 0, 0, 0.08)',
    '--theme-shadow-dropdown': '0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -2px rgba(0, 0, 0, 0.06)',
    '--theme-shadow-modal': '0 20px 25px -5px rgba(0, 0, 0, 0.12), 0 8px 10px -6px rgba(0, 0, 0, 0.08)',
  },
  emerald: {
    '--theme-bg-base': '#f0fdf4',
    '--theme-bg-sidebar': '#ffffff',
    '--theme-bg-card': '#ffffff',
    '--theme-bg-elevated': '#dcfce7',
    '--theme-bg-hover': '#bbf7d0',
    '--theme-bg-input': '#ffffff',
    '--theme-primary': '#10b981',
    '--theme-primary-light': '#d1fae5',
    '--theme-primary-dark': '#059669',
    '--theme-text-primary': '#064e3b',
    '--theme-text-secondary': '#047857',
    '--theme-text-muted': '#6ee7b7',
    '--theme-text-disabled': '#bbf7d0',
    '--theme-text-inverse': '#ffffff',
    '--theme-border-default': '#bbf7d0',
    '--theme-border-focus': '#10b981',
    '--theme-border-subtle': '#dcfce7',
    '--theme-success': '#22c55e',
    '--theme-success-light': '#dcfce7',
    '--theme-warning': '#f59e0b',
    '--theme-warning-light': '#fef3c7',
    '--theme-error': '#ef4444',
    '--theme-error-light': '#fee2e2',
    '--theme-info': '#3b82f6',
    '--theme-info-light': '#dbeafe',
    '--theme-chart-1': '#10b981',
    '--theme-chart-2': '#8b5cf6',
    '--theme-chart-3': '#f59e0b',
    '--theme-chart-4': '#22c55e',
    '--theme-chart-5': '#ef4444',
    '--theme-shadow-card': '0 4px 12px rgba(0, 0, 0, 0.06)',
    '--theme-shadow-card-hover': '0 8px 30px rgba(0, 0, 0, 0.08)',
    '--theme-shadow-dropdown': '0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -2px rgba(0, 0, 0, 0.06)',
    '--theme-shadow-modal': '0 20px 25px -5px rgba(0, 0, 0, 0.12), 0 8px 10px -6px rgba(0, 0, 0, 0.08)',
  },
  purple: {
    '--theme-bg-base': '#faf5ff',
    '--theme-bg-sidebar': '#ffffff',
    '--theme-bg-card': '#ffffff',
    '--theme-bg-elevated': '#f3e8ff',
    '--theme-bg-hover': '#e9d5ff',
    '--theme-bg-input': '#ffffff',
    '--theme-primary': '#8b5cf6',
    '--theme-primary-light': '#ede9fe',
    '--theme-primary-dark': '#7c3aed',
    '--theme-text-primary': '#4c1d95',
    '--theme-text-secondary': '#6d28d9',
    '--theme-text-muted': '#c4b5fd',
    '--theme-text-disabled': '#ddd6fe',
    '--theme-text-inverse': '#ffffff',
    '--theme-border-default': '#e9d5ff',
    '--theme-border-focus': '#8b5cf6',
    '--theme-border-subtle': '#f3e8ff',
    '--theme-success': '#22c55e',
    '--theme-success-light': '#dcfce7',
    '--theme-warning': '#f59e0b',
    '--theme-warning-light': '#fef3c7',
    '--theme-error': '#ef4444',
    '--theme-error-light': '#fee2e2',
    '--theme-info': '#3b82f6',
    '--theme-info-light': '#dbeafe',
    '--theme-chart-1': '#8b5cf6',
    '--theme-chart-2': '#0ea5e9',
    '--theme-chart-3': '#f59e0b',
    '--theme-chart-4': '#22c55e',
    '--theme-chart-5': '#ef4444',
    '--theme-shadow-card': '0 4px 12px rgba(0, 0, 0, 0.06)',
    '--theme-shadow-card-hover': '0 8px 30px rgba(0, 0, 0, 0.08)',
    '--theme-shadow-dropdown': '0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -2px rgba(0, 0, 0, 0.06)',
    '--theme-shadow-modal': '0 20px 25px -5px rgba(0, 0, 0, 0.12), 0 8px 10px -6px rgba(0, 0, 0, 0.08)',
  },
  gold: {
    '--theme-bg-base': '#F5F2EB',
    '--theme-bg-sidebar': '#FFFFFF',
    '--theme-bg-card': '#FFFFFF',
    '--theme-bg-elevated': '#FAF8F4',
    '--theme-bg-hover': '#F8F5F0',
    '--theme-bg-input': '#FFFFFF',
    '--theme-primary': '#A97A1F',
    '--theme-primary-light': '#DDB35A',
    '--theme-primary-dark': '#8B6914',
    '--theme-text-primary': '#1A1A1A',
    '--theme-text-secondary': '#4A4A4A',
    '--theme-text-muted': '#7A7A7A',
    '--theme-text-disabled': '#B0A89C',
    '--theme-text-inverse': '#FFFFFF',
    '--theme-border-default': '#E0D8CC',
    '--theme-border-focus': '#A97A1F',
    '--theme-border-subtle': '#F0ECE6',
    '--theme-success': '#1B5E20',
    '--theme-success-light': '#E8F5E9',
    '--theme-warning': '#E67E22',
    '--theme-warning-light': '#FEF3E2',
    '--theme-error': '#B71C1C',
    '--theme-error-light': '#FFEBEE',
    '--theme-info': '#3B82F6',
    '--theme-info-light': '#DBEAFE',
    '--theme-chart-1': '#A97A1F',
    '--theme-chart-2': '#C89B3C',
    '--theme-chart-3': '#DDB35A',
    '--theme-chart-4': '#E8C980',
    '--theme-chart-5': '#F6ECD7',
    '--theme-shadow-card': '0 4px 12px rgba(0, 0, 0, 0.06)',
    '--theme-shadow-card-hover': '0 8px 30px rgba(0, 0, 0, 0.08)',
    '--theme-shadow-dropdown': '0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -2px rgba(0, 0, 0, 0.06)',
    '--theme-shadow-modal': '0 20px 25px -5px rgba(0, 0, 0, 0.12), 0 8px 10px -6px rgba(0, 0, 0, 0.08)',
  },
  // ── Premium Dark Gold (NEW) ──
  'dark-gold': {
    '--theme-bg-base': '#1A1A1A',
    '--theme-bg-sidebar': '#242424',
    '--theme-bg-card': '#2A2A2A',
    '--theme-bg-elevated': '#333333',
    '--theme-bg-hover': '#3D3D3D',
    '--theme-bg-input': '#2A2A2A',
    '--theme-primary': '#C89B3C',
    '--theme-primary-light': '#DDB35A',
    '--theme-primary-dark': '#A97A1F',
    '--theme-text-primary': '#F5F2EB',
    '--theme-text-secondary': '#C8C0B4',
    '--theme-text-muted': '#8A8278',
    '--theme-text-disabled': '#5A5248',
    '--theme-text-inverse': '#1A1A1A',
    '--theme-border-default': '#3D3D3D',
    '--theme-border-focus': '#C89B3C',
    '--theme-border-subtle': '#333333',
    '--theme-success': '#4CAF50',
    '--theme-success-light': '#1B5E20',
    '--theme-warning': '#F59E0B',
    '--theme-warning-light': '#92400E',
    '--theme-error': '#EF5350',
    '--theme-error-light': '#B71C1C',
    '--theme-info': '#42A5F5',
    '--theme-info-light': '#0D47A1',
    '--theme-chart-1': '#C89B3C',
    '--theme-chart-2': '#DDB35A',
    '--theme-chart-3': '#E8C980',
    '--theme-chart-4': '#F6ECD7',
    '--theme-chart-5': '#A97A1F',
    '--theme-shadow-card': '0 4px 12px rgba(0, 0, 0, 0.3)',
    '--theme-shadow-card-hover': '0 8px 30px rgba(0, 0, 0, 0.4)',
    '--theme-shadow-dropdown': '0 4px 6px -1px rgba(0, 0, 0, 0.3), 0 2px 4px -2px rgba(0, 0, 0, 0.2)',
    '--theme-shadow-modal': '0 20px 25px -5px rgba(0, 0, 0, 0.4), 0 8px 10px -6px rgba(0, 0, 0, 0.3)',
  },
  // ── Pure White Minimal (NEW) ──
  'white-minimal': {
    '--theme-bg-base': '#FFFFFF',
    '--theme-bg-sidebar': '#FFFFFF',
    '--theme-bg-card': '#FFFFFF',
    '--theme-bg-elevated': '#F8F8F8',
    '--theme-bg-hover': '#F0F0F0',
    '--theme-bg-input': '#FFFFFF',
    '--theme-primary': '#1A1A1A',
    '--theme-primary-light': '#4A4A4A',
    '--theme-primary-dark': '#000000',
    '--theme-text-primary': '#1A1A1A',
    '--theme-text-secondary': '#4A4A4A',
    '--theme-text-muted': '#7A7A7A',
    '--theme-text-disabled': '#B0B0B0',
    '--theme-text-inverse': '#FFFFFF',
    '--theme-border-default': '#E5E5E5',
    '--theme-border-focus': '#1A1A1A',
    '--theme-border-subtle': '#F0F0F0',
    '--theme-success': '#2E7D32',
    '--theme-success-light': '#E8F5E9',
    '--theme-warning': '#E67E22',
    '--theme-warning-light': '#FEF3E2',
    '--theme-error': '#D32F2F',
    '--theme-error-light': '#FFEBEE',
    '--theme-info': '#1976D2',
    '--theme-info-light': '#E3F2FD',
    '--theme-chart-1': '#1A1A1A',
    '--theme-chart-2': '#4A4A4A',
    '--theme-chart-3': '#7A7A7A',
    '--theme-chart-4': '#B0B0B0',
    '--theme-chart-5': '#D0D0D0',
    '--theme-shadow-card': '0 4px 12px rgba(0, 0, 0, 0.04)',
    '--theme-shadow-card-hover': '0 8px 30px rgba(0, 0, 0, 0.06)',
    '--theme-shadow-dropdown': '0 4px 6px -1px rgba(0, 0, 0, 0.04), 0 2px 4px -2px rgba(0, 0, 0, 0.02)',
    '--theme-shadow-modal': '0 20px 25px -5px rgba(0, 0, 0, 0.06), 0 8px 10px -6px rgba(0, 0, 0, 0.04)',
  }
};